spring:
  application:
    name: denodo-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  servlet:
    context-path: /api

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
#  type-aliases-package: com.denodo.platform.api.post.model
#  configuration:
#    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.denodo.platform.api: info
    com.denodo.platform.api.post.mapper: info